### ISSUE TITLE
File count

### ISSUE THREAD

**Issue by ghost** [XtremeRahul/gdrive_folder_size#1]
GDC = gdrive_folder_size

Only issue is GDC count trash files also

**Comment by XtremeRahul** [comment]
> GDC = gdrive_folder_size
> 
> Only issue is GDC count trash files also

It might! Because trash files are still linked to the folder you deleted from!

**Comment by ghost** [comment]
> > GDC = gdrive_folder_size
> > Only issue is GDC count trash files also
> 
> It might! Because trash files are still linked to the folder you deleted from!

**Comment by ghost** [comment]
Any further development on it
